### ISSUE TITLE
Does not correctly convert to the FlaME compatible format.

### ISSUE THREAD

**Issue by Arithyce** [Warzone2100/maptools-cli#23]
Maps converted to the old FlaME compatible "bjo" and "lev" formats do not open in flame as they are not properly converted (for FlaME compatibility).

In the .lev file, the "game" field needs to have the full path to the .gam file, in the converted version it only has the filename of the .gam file.

It is possible to fix this in FlaME, since development has continued, so it may not need to be corrected in maptools. This will be posted as an issue in the FlaME repo aswell.

**Comment by past-due** [comment]
Please see https://github.com/Warzone2100/maptools-cli/releases/tag/v1.2.5

**Comment by Arithyce** [comment]
> Please see https://github.com/Warzone2100/maptools-cli/releases/tag/v1.2.5

It works for me now. Fixed.
